use genanki_rs::{Deck, Field, Model, Note, Template};
use serde::{Deserialize, Serialize};
use time::{Date, UtcDateTime};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CEDictEntry {
    pub zh: String,
    pub pinyin: String,
    pub definition: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub date: Date,
    pub font: String,
    pub model: String,
    pub entries: Vec<CEDictEntry>,
}

impl Config {
    pub fn from_path(path: &str) -> Option<Self> {
        serde_json::from_str(&std::fs::read_to_string(path).ok()?).ok()
    }

    pub fn new() -> Self {
        let date = UtcDateTime::now().date();

        Self {
            date,
            font: "unifont.ttf".into(),
            model: "tiny.bin".into(),
            entries: Vec::new(),
        }
    }

    pub fn save(&self, path: &str) -> bool {
        if let Ok(s) = serde_json::to_string(self) {
            std::fs::write(path, &s).is_ok()
        } else {
            false
        }
    }

    pub fn export(&self, path: &str) -> bool {
        let model = Model::new(
            rand::random_range(0..i64::MAX),
            "Model",
            vec![Field::new("Question"), Field::new("Answer")],
            vec![Template::new("Card")
                .qfmt("{{Question}}")
                .afmt(r#"{{FrontSide}}<hr id="answer">{{Answer}}"#)],
        );

        let mut deck = Deck::new(
            rand::random_range(0..i64::MAX),
            "lange-deck",
            "Deck generated by LangE",
        );

        for card in self.entries.iter() {
            if let Ok(note) = Note::new(model.clone(), vec![&card.zh, &card.pinyin]) {
                deck.add_note(note);
            }

            if let Ok(note) = Note::new(model.clone(), vec![&card.zh, &card.definition]) {
                deck.add_note(note);
            }

            if let Ok(note) = Note::new(model.clone(), vec![&card.definition, &card.pinyin]) {
                deck.add_note(note);
            }
        }

        deck.write_to_file(path).is_ok()
    }

    pub fn lookup(&self, zh: &str) -> Option<&CEDictEntry> {
        self.entries.iter().find(|e| e.zh == zh)
    }

    pub fn insert(&mut self, entry: CEDictEntry) {
        self.entries.push(entry);
    }
}
